# Replace the text below to customize your site
site_name: ALBERT VILA - MDEF Logbook
site_description: Master in Design for Emergent Futures
site_author: Albert Vila
copyright: Copyleft 2023 "Albert Vila" - GNU Free Documentation License
repo_name: 'ALBERT-MDEF'
site_url: https://avilabon.github.io/MDEF_Albert/
repo_url: 'https://github.com/avilabon/MDEF_Albert'


# Arbre web i de navegació
nav:
  - Home: index.md
  - About: about/me.md
  - Term 1:
     - Landing:  term1/01-Landing.md
     - Documenting design: term1/02-Documenting.md
     - Design Studio:
        - Roles of prototyping: term1/03-DesignStudio/03-RolesOfPrototyping.md
        - Atlas of Weak Signals: term1/03-DesignStudio/03-AtlasOfWeakSignals.md
        - Narratives Storytelling: term1/03-DesignStudio/03-PersonalNarrativesCollectiveStorytelling.md
        - Intervention 01: term1/03-DesignStudio/03-Intervention01.md
        - Intervention 02: term1/03-DesignStudio/03-Intervention02.md
     - The Machine Paradox:
        - The Machine Paradox: term1/05-TheMachineParadox/05-TheMachineParadox.md
        - 3D Printer forensic report: term1/05-TheMachineParadox/05-ForensicReport.md
        - Life Xpectancy: term1/05-TheMachineParadox/05-TheMagicMachine.md
     - Living With Your Own Ideas: term1/06-LivingWithYourOwnIdeas.md
     - Bio Agri Zero: term1/07-BiologyZero.md
     - Design With Others: term1/08-DesignWithOthers.md
     - Extended Intelligences: term1/09-ExtendedIntelligences.md
     - Design Dialogs: term1/10-DesignDialogs.md
  - Term 2:
      - Design Studio 02:
        - Design Studio 02 - Intro: term2/T2-01-DesignStudio02/T2-01-01DesignStudioIntro.md
        - Intervention T2-01: term2/T2-01-DesignStudio02/T2-01-02Intervention1.md
      - Designing in State of Climate Emergency: term2/T2-02-DesigningStateClimateEmergency.md
      - Communicating Ideas:
        - Communicating ideas: term2/T2-03-CommunicatingIdeas/T2-03-01-CI_Reflections.md  
        - Tandem exercice: term2/T2-03-CommunicatingIdeas/T2-03-02-CI_Tandem.md
      - Future Talks:
        - Design With Values-Distributed Design: term2/T2-04-FutureTalks/T2-04-01-DesignWithValues-DD.md
        - Networks of Co-Responsability-WetLab: term2/T2-04-FutureTalks/T2-04-02-WetLab.md
        - Internet Tour: term2/T2-04-FutureTalks/T2-04-03-InternetTour.md
        - Radical Situatedness: term2/T2-04-FutureTalks/T2-04-04-RadicalSituatedness.md
      - Digital Prototyping for Design (DP4D):
        - DP4D Module 1: term2/T2-05-DigitalPrototypingForDesign/T2-05-01-DP4D_Module1.md
        - DP4D Module 2: term2/T2-05-DigitalPrototypingForDesign/T2-05-02-DP4D_Module2.md
        - DP4D Module 3: term2/T2-05-DigitalPrototypingForDesign/T2-05-02-DP4D_Module3.md
        - DP4D Microchallenge 1: term2/T2-05-DigitalPrototypingForDesign/T2-05-03-DP4D_Microchallenge1.md
        - DP4D Microchallenge 2: term2/T2-05-DigitalPrototypingForDesign/T2-05-03-DP4D_Microchallenge2.md
      - Designing with Collective Intelligence: term2/T2-04-DesigningWithCollectiveIntelligence.md
      - Measuring the World: term2/T2-06-MeasuringTheWorld.md
      - Designing with Extended Intelligences: term2/T2-07-DesigningWithExtendedIntelligences.md
      - Research trip: term2/T2-08-ResearchTrip.md
  - Term 3:
      - Design studio 03:
        - Atlas of weak signals 2: term3/T3-01-DesignStudio03/T3-01-01AtlasOfWeakSignals2.md
      - Future talks 03:
        - Saul Baeza (DOES): term3/T3-02-FutureTalks03/T3-02-01-DOES.md
        - Helen Torres (D. Haraway): term3/T3-02-FutureTalks03/T3-02-02-HELEN.md
      - Communicating ideas 2:
        - Communication ideas 2: term3/T3-03-CommunicatingIdeas2/T3-03-01-CommunicationIdeas02.md

  - Master thesis:
      - Brand core: masterProject/MP-01-BrandCore.md
      - Project sheet: masterProject/MP-02-ProjectSheet.md
      - Communication strategy: masterProject/MP-03-CommunicationStrategy.md
      - Tandem project: 
        - Tandem project 1: term2/T2-03-CommunicatingIdeas/T2-03-02-CI_Tandem.md
        - Bizarre Love Triangle Pictorial: masterProject/MP-04-TandemProject/MP-04-02-BizLovTriPic.md

     # - Poster:   
      
    

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/vilagual/
    - icon: fontawesome/brands/github
      link: "https://github.com/avilabon/"


theme:
  name: material
  palette:
    # scheme: slate
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: grey
    accent: lime
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  #  icon:
  #    logo: material/memory
  logo: logo.png
  favicon: images/A_rodona_negre2.svg
  # favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
     
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed
  - tables

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css


