# Replace the text below to customize your site
site_name: ALBERT VILA - MDEF Logbook
site_description: Master in Design for Emergent Futures
site_author: Albert Vila
copyright: Copyleft 2023 "Albert Vila" - GNU Free Documentation License
repo_name: 'ALBERT-MDEF'
site_url: https://avilabon.github.io/MDEF_Albert/
repo_url: 'https://github.com/avilabon/MDEF_Albert'


# Arbre web i de navegació
nav:
  - Home: index.md
  - About: about/me.md
  - Term 1:
     - Landing:  term1/01-Landing.md
     - Documenting design: term1/02-Documenting.md
     - Design Studio:
        - Roles of prototyping: term1/03-DesignStudio/03-RolesOfPrototyping.md
        - Atlas of Weak Signals: term1/03-DesignStudio/03-AtlasOfWeakSignals.md
        - Narratives Storytelling: term1/03-DesignStudio/03-PersonalNarrativesCollectiveStorytelling.md
        - Intervention 01: term1/03-DesignStudio/03-Intervention01.md
        - Intervention 02: term1/03-DesignStudio/03-Intervention02.md
     - The Machine Paradox:
        - The Machine Paradox: term1/05-TheMachineParadox/05-TheMachineParadox.md
        - 3D Printer forensic report: term1/05-TheMachineParadox/05-ForensicReport.md
        - Life Xpectancy: term1/05-TheMachineParadox/05-TheMagicMachine.md
     - Living With Your Own Ideas: term1/06-LivingWithYourOwnIdeas.md
     - Bio Agri Zero: term1/07-BiologyZero.md
     - Design With Others: term1/08-DesignWithOthers.md
     - Extended Intelligences: term1/09-ExtendedIntelligences.md
     - Design Dialogs: term1/10-DesignDialogs.md
  - Term 2:
      - Design Studio 02:
        - Design Studio 02: term2/T2-01-DesignStudio02/T2-01-DesignStudioIntro.md
      - Designing in State of Climate Emergency: term2/T2-02-DesigningStateClimateEmergency.md
      - Communication Ideas: term2/T2-03-CommunicatingIdeas.md
      - Digital Prototyping for Design (DP4D):
        - DP4D Module 1: term2/T2-05-DigitalPrototypingForDesign/T2-05-01-DP4D_Module1.md
        - DP4D Module 2: term2/T2-05-DigitalPrototypingForDesign/T2-05-01-DP4D_Module2.md
        - DP4D Microchallenge 1: term2/T2-05-DigitalPrototypingForDesign/T2-05-01-DP4D_Microchallenge1.md
      - Designing with Collective Intelligence: term2/T2-04-DesigningWithCollectiveIntelligence.md
      - Measuring the World: term2/T2-06-MeasuringTheWorld.md
      - Designing with Extended Intelligences: term2/T2-04-DesigningWithExtendedIntelligences.md

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/vilagual/
    - icon: fontawesome/brands/github
      link: "https://github.com/avilabon/"


theme:
  name: material
  palette:
    # scheme: slate
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: grey
    accent: lime
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  #  icon:
  #    logo: material/memory
  logo: logo.png
  favicon: images/A_rodona_negre2.svg
  # favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
     
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed
  - tables

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css


